name: Build APK

on:
  repository_dispatch:
    types: [build-apk]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.jks

      - name: Replace Placeholders
        run: |

          find . -type f -exec sed -i "s|APP_NAME_PLACEHOLDER|${{ github.event.client_payload.appName }}|g" {} +

          find . -type f -exec sed -i "s|URL_PLACEHOLDER|${{ github.event.client_payload.websiteUrl }}|g" {} +

          find . -type f -exec sed -i "s|PACKAGE_PLACEHOLDER|${{ github.event.client_payload.packageName }}|g" {} +

          find . -type f -exec sed -i "s|BANNER_AD_ID_PLACEHOLDER|${{ github.event.client_payload.bannerAdId }}|g" {} +

          find . -type f -exec sed -i "s|INTERSTITIAL_AD_ID_PLACEHOLDER|${{ github.event.client_payload.interstitialAdId }}|g" {} +

      - name: Build APK
        run: chmod +x gradlew && ./gradlew assembleRelease

      - name: Rename APK
        run: |
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/${{ github.event.client_payload.packageName }}.apk

      - name: Upload APK to Hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: app/build/outputs/apk/release/
          server-dir: /